### ISSUE TITLE
ABC120 の問題のテストケースへのリンクが 404 してる

### ISSUE THREAD

**Issue by kmyk** [tatsumack/atcoder-testcase-extension#3]
例: https://atcoder.jp/contests/abc120/submissions/6730121 -> https://www.dropbox.com/sh/arnpe0ef5wds8cv/AACcyfsQ9ub7coOcxk02vV-La/ABC120/C/in?preview=sample_01.in

**Comment by tatsumack** [comment]
報告ありがとうございます！修正しました
